[program:techpace-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/techpace/artisan queue:work redis --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/techpace/storage/logs/worker.log
stopwaitsecs=3600
